import assert from "node:assert/strict";
import { validatePlaylist } from "../scripts/inventory_playlist.mjs";
import { normalizeYouTubeUrl } from "../scripts/normalize_sources.mjs";
import { cleanTranscript } from "../scripts/clean_transcript.mjs";
import { sanitizeFilename } from "../scripts/sanitize_filename.mjs";

const playlist = validatePlaylist({
  reportedCount: 2,
  videos: [
    { id: "rRa9td4oe7k", title: "One", creator: "Creator", canonicalUrl: "ignored" },
    { id: "ib74sLgjIBM", title: "Two", creator: "Creator", canonicalUrl: "ignored" }
  ]
});
assert.equal(playlist.collectedCount, 2);
assert.equal(playlist.videos[0].canonicalUrl, "https://www.youtube.com/watch?v=rRa9td4oe7k");
assert.throws(() => validatePlaylist({ videos: [{ id: "bad", title: "x", creator: "y" }] }));
assert.throws(() => validatePlaylist({ videos: [
  { id: "rRa9td4oe7k", title: "One", creator: "Creator" },
  { id: "rRa9td4oe7k", title: "Duplicate", creator: "Creator" }
] }));

assert.equal(normalizeYouTubeUrl("https://www.youtube.com/watch?v=rRa9td4oe7k&list=x"), "rRa9td4oe7k");
assert.equal(normalizeYouTubeUrl("https://youtu.be/ib74sLgjIBM"), "ib74sLgjIBM");
assert.equal(normalizeYouTubeUrl("https://www.youtube.com/shorts/GguuI7EJwVU"), "GguuI7EJwVU");

const rawTranscript = `# Transcript: Example

Source video: https://example.test

## Transcript
[0:01] This is useful text and This is useful text and this is the next idea.
[0:30] [music] A second paragraph &gt;&gt; with no metadata.
---
Generated by provider`;
const cleaned = cleanTranscript(rawTranscript);
assert.match(cleaned, /This is useful text/);
assert.doesNotMatch(cleaned, /Source video|Generated by provider|\[0:01\]|\[music\]/);

assert.equal(sanitizeFilename("A:/Title? with *invalid* chars."), "ATitle with invalid chars");

console.log("PASS: helper tests");
